name = "scansci-journal-search"
main = "src/journal-search-worker.js"
compatibility_date = "2026-02-26"
workers_dev = false

[[routes]]
pattern = "www.scansci.com/api/journals/search*"
zone_name = "scansci.com"

[[d1_databases]]
binding = "DB"
database_name = "scansci_auth"
database_id = "4ea255cf-6c0e-4bd5-bafb-16e6bfda7689"
